# Generated by Django 5.2.1 on 2025-05-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
